#ifndef _twins_strints_text_ids_h__
#define _twins_strints_text_ids_h__

#define StrId_Cantgetsystemrootdirectory                13001
#define StrId_Cantloadshelliconslist                    13002
#define StrId_Exit                                      13003
#define StrId_Turnonoffdisplayofhiddenfiles             13004
#define StrId_Selectleftdisk                            13005
#define StrId_Selectrightdisk                           13006
#define StrId_Switchpanel                               13007
#define StrId_Rename                                    13008
#define StrId_View                                      13009
#define StrId_Edit                                      13010
#define StrId_Create                                    13011
#define StrId_Copy                                      13012
#define StrId_Move                                      13013
#define StrId_Createdir                                 13014
#define StrId_Terminal                                  13015
#define StrId_Movetotrash                               13016
#define StrId_Delete                                    13017
#define StrId_Editpath                                  13018
#define StrId_Showhistory                               13019
#define StrId_Addpathtobookmarks                        13020
#define StrId_Invertselection                           13021
#define StrId_Appendselection                           13022
#define StrId_Subtractselection                         13023
#define StrId_Openentryundercursor                      13024
#define StrId_Showproperties                            13025
#define StrId_Selectentryundercursor                    13026
#define StrId_Cursorup                                  13027
#define StrId_Cursordown                                13028
#define StrId_Cursortobegin                             13029
#define StrId_Cursortoend                               13030
#define StrId_Cursortopageup                            13031
#define StrId_Cursortopagedown                          13032
#define StrId_Activatecommandline                       13033
#define StrId_Showcommandlinehistory                    13034
#define StrId_Currentpathtocommandline                  13035
#define StrId_Entryundercursorfilenametocommandlin      13036
#define StrId_Search                                    13037
#define StrId_Subdirectorysize                          13038
#define StrId_Allsubdirectoriessizes                    13039
#define StrId_About                                     13040
#define StrId_Options                                   13041
#define StrId_Panels                                    13042
#define StrId_Utils                                     13043
#define StrId_Filemanager                               13044
#define StrId_Appearance                                13045
#define StrId_Reportsandstatistics                      13046
#define StrId_Exts_All                                  13047
#define StrId_Exts_Withoutextension                     13048
#define StrId_Exts_Executables                          13049
#define StrId_Exts_Components                           13050
#define StrId_Exts_Pictures                             13051
#define StrId_Exts_Audio                                13052
#define StrId_Exts_Video                                13053
#define StrId_Exts_Sources                              13054
#define StrId_Exts_SourcesC                             13055
#define StrId_Exts_SourcesCC                            13056
#define StrId_Confirmrequest                            13057
#define StrId_Replace                                   13058
#define StrId_Autorenamesourcefile                      13059
#define StrId_Autorenamedestinationfile                 13060
#define StrId_Export                                    13061
#define StrId_Import                                    13062
#define StrId_Apply                                     13063
#define StrId_Cancel                                    13064
#define StrId_Choosecolumns                             13065
#define StrId_Withoutsort                               13066
#define StrId_Bydefault                                 13067
#define StrId_Launchs                                   13068
#define StrId_Loadings8fsec                             13069
#define StrId_Renames                                   13070
#define StrId_ErrordSunableentertodirectorys            13071
#define StrId_Watchingfors                              13072
#define StrId_Watchingforsfinished                      13073
#define StrId_Enterdirectoryfoldername                  13074
#define StrId_Newdirectoryfolder                        13075
#define StrId_Creatingdirectorys                        13076
#define StrId_Enterfilename                             13077
#define StrId_Newfile                                   13078
#define StrId_Creatingfiles                             13079
#define StrId_Copyfilesinamountofd                      13080
#define StrId_Select                                    13081
#define StrId_Unselect                                  13082
#define StrId_Kb                                        13083
#define StrId_Ssfromssfilesdfromddirsdfromd             13084
#define StrId_Feedback                                  13085
#define StrId_Close                                     13086
#define StrId_Testingbuildnolicenserequired             13087
#define StrId_Authors                                   13088
#define StrId_Thanksforassistance                       13089
#define StrId_Pause                                     13090
#define StrId_Inbackground                              13091
#define StrId_SsMb                                      13092
#define StrId_SMb                                       13093
#define StrId_Additionally                              13094
#define StrId_Hide                                      13095
#define StrId_Replacefiles                              13096
#define StrId_Yes                                       13097
#define StrId_Yesall                                    13098
#define StrId_Skip                                      13099
#define StrId_Replaceolder                              13100
#define StrId_Skipall                                   13101
#define StrId_Appendwrite                               13102
#define StrId_Compare                                   13103
#define StrId_Renameexistingfile                        13104
#define StrId_Autorenamesourcefiles                     13105
#define StrId_Autorenameexistancefiles                  13106
#define StrId_Renameallwithsamedateandolder             13107
#define StrId_Copyallfileswithgreatersize               13108
#define StrId_Copyallfileswithsmallersize               13109
#define StrId_Sbytess                                   13110
#define StrId_Simple                                    13111
#define StrId_Extended                                  13112
#define StrId_Normal                                    13113
#define StrId_Emacs                                     13114
#define StrId_Awk                                       13115
#define StrId_Grep                                      13116
#define StrId_Egrep                                     13117
#define StrId_Seconds                                   13118
#define StrId_Minutes                                   13119
#define StrId_Hours                                     13120
#define StrId_Days                                      13121
#define StrId_Weeks                                     13122
#define StrId_Months                                    13123
#define StrId_Years                                     13124
#define StrId_Bytes                                     13125
#define StrId_Kilobytes                                 13126
#define StrId_Megabytes                                 13127
#define StrId_Gigabytes                                 13128
#define StrId_Start                                     13129
#define StrId_Goto                                      13130
#define StrId_Topanel                                   13131
#define StrId_ErrordS                                   13132
#define StrId_Ready                                     13133
#define StrId_8fsec                                     13134
#define StrId_Ok                                        13135
#define StrId_File                                      13136
#define StrId_Filea                                     13137
#define StrId_Files                                     13138
#define StrId_Copyfiles                                 13139
#define StrId_Copysto                                   13140
#define StrId_Deletingfiles                             13141
#define StrId_Reallywanttodeletethefilestothetrash      13142
#define StrId_Movefiles                                 13143
#define StrId_Movesto                                   13144
#define StrId_Searchinfile                              13145
#define StrId_Searchins                                 13146
#define StrId_Launchss                                  13148
#define StrId_Launcheditorfors                          13149
#define StrId_Configuration                             13150
#define StrId_Twins                                     13151
#define StrId_Experimentalfilemanager                   13152
#define StrId_Language                                  13153
#define StrId_Regularexpression                         13154
#define StrId_Filess                                    13155
#define StrId_Directories                               13156
#define StrId_Templates                                 13157
#define StrId_Closedialogaftertemplateselecting         13158
#define StrId_ReplaceDc                                 13159
#define StrId_To                                        13160
#define StrId_SaveNTFSattributes                        13161
#define StrId_Skipinaccessiblefiles                     13162
#define StrId_Replacedeletehiddensystemfiles            13163
#define StrId_Replaceoptions                            13164
#define StrId_Pattern                                   13165
#define StrId_Searchbyfilename                          13166
#define StrId_Casesensitive                             13167
#define StrId_Path                                      13168
#define StrId_Contains                                  13169
#define StrId_Wholewordsonly                            13170
#define StrId_Ignorecase                                13171
#define StrId_Datefrom                                  13172
#define StrId_To2                                       13173
#define StrId_Notolder                                  13174
#define StrId_Size                                      13175
#define StrId_Attributes                                13176
#define StrId_Readonly                                  13177
#define StrId_Directory                                 13178
#define StrId_Archive                                   13179
#define StrId_System                                    13180
#define StrId_Compressed                                13181
#define StrId_Hidden                                    13182
#define StrId_Encrypted                                 13183
#define StrId_Searchduplicates                          13184
#define StrId_Byname                                    13185
#define StrId_Bysize                                    13186
#define StrId_Bycontent                                 13187
#define StrId_Searchresults                             13188
#define StrId_Codepage                                  13189
#define StrId_Regularexpressiontype                     13190
#define StrId_Backwards                                 13191
#define StrId_Hexcode                                   13192
#define StrId_MichaelNikonov                            13193
#define StrId_TomywifeNadineallowedmetoworkevening      13194
#define StrId_IndependedDeveloper2012                   13195
#define StrId_Unknown                                   13196
#define StrId_Unmounted                                 13197
#define StrId_Removable                                 13198
#define StrId_Hdd                                       13199
#define StrId_Sharemount                                13200
#define StrId_Optical                                   13201
#define StrId_Ramdisk                                   13202
#define StrId_Floppy                                    13203
#define StrId_Network                                   13204
#define StrId_Plugins                                   13205
#define StrId_Unmounted2                                13206
#define StrId_Sfromsfree                                13207
#define StrId_Showhiddenfiles                           13208
#define StrId_Name                                      13209
#define StrId_Type                                      13210
#define StrId_SizeDc                                    13211
#define StrId_Date                                      13212
#define StrId_AttributesDc                              13213
#define StrId_Shelltype                                 13214
#define StrId_Configurationhaspendingchanges            13215
#define StrId_Doyoureallywanttoclosethedialog           13216
#define StrId_Internalviewer                            13217
#define StrId_Configurationexportimportfailure          13218
#define StrId_Error                                     13219
#define StrId_Exportfailure                             13220
#define StrId_Importfailure                             13221
#define StrId_RestartMainframe                          13222
#define StrId_FileMenu                                  13223
#define StrId_TWINS                                     13224
#define StrId_RestartMainframeMenu                      13225
#define StrId_ExitMenu                                  13226
#define StrId_ViewMenu                                  13227
#define StrId_Configuration2                            13228
#define StrId_Help                                      13229
#define StrId_AboutMenu                                 13230
#define StrId_HMmdY                                     13231
#define StrId_OnlyforTESTing                            13232
#define StrId_Twinsfilemanager                          13233
#define StrId_WTLTabcontrolstuff                        13234
#define StrId_WTLCoolmenubar                            13235
#define StrId_ShellmenusdragndropWTLusefullystuff       13236
#define StrId_NotImplementedYet                         13237
#define StrId_Searchresult                              13238
#define StrId_Russian                                   13239
#define StrId_English                                   13240

#endif /* _twins_strints_text_ids_h__ */
