DA_BITMASK_TO_STR(LVS_ICON           ); /* 0x0000 */
DA_BITMASK_TO_STR(LVS_REPORT         ); /* 0x0001 */
DA_BITMASK_TO_STR(LVS_SMALLICON      ); /* 0x0002 */
DA_BITMASK_TO_STR(LVS_LIST           ); /* 0x0003 */
DA_BITMASK_TO_STR(LVS_TYPEMASK       ); /* 0x0003 */
DA_BITMASK_TO_STR(LVS_SINGLESEL      ); /* 0x0004 */
DA_BITMASK_TO_STR(LVS_SHOWSELALWAYS  ); /* 0x0008 */
DA_BITMASK_TO_STR(LVS_SORTASCENDING  ); /* 0x0010 */
DA_BITMASK_TO_STR(LVS_SORTDESCENDING ); /* 0x0020 */
DA_BITMASK_TO_STR(LVS_SHAREIMAGELISTS); /* 0x0040 */
DA_BITMASK_TO_STR(LVS_NOLABELWRAP    ); /* 0x0080 */
DA_BITMASK_TO_STR(LVS_AUTOARRANGE    ); /* 0x0100 */
DA_BITMASK_TO_STR(LVS_EDITLABELS     ); /* 0x0200 */
#if (_WIN32_IE >= 0x0300)
DA_BITMASK_TO_STR(LVS_OWNERDATA      ); /* 0x1000 */
#endif
DA_BITMASK_TO_STR(LVS_NOSCROLL       ); /* 0x2000 */
DA_BITMASK_TO_STR(LVS_TYPESTYLEMASK  ); /* 0xfc00 */
//DA_BITMASK_TO_STR(LVS_ALIGNTOP     ); /* 0x0000 */
DA_BITMASK_TO_STR(LVS_ALIGNLEFT      ); /* 0x0800 */
DA_BITMASK_TO_STR(LVS_ALIGNMASK      ); /* 0x0c00 */
DA_BITMASK_TO_STR(LVS_OWNERDRAWFIXED ); /* 0x0400 */
DA_BITMASK_TO_STR(LVS_NOCOLUMNHEADER ); /* 0x4000 */
DA_BITMASK_TO_STR(LVS_NOSORTHEADER   ); /* 0x8000 */
