DA_BEG_WT_GROUP(WT_Edit)
/*
 * Edit Control Notification Codes
 */
DA_NUM_TO_STR(EN_SETFOCUS );
DA_NUM_TO_STR(EN_KILLFOCUS);
DA_NUM_TO_STR(EN_CHANGE   );
DA_NUM_TO_STR(EN_UPDATE   );
DA_NUM_TO_STR(EN_ERRSPACE );
DA_NUM_TO_STR(EN_MAXTEXT  );
DA_NUM_TO_STR(EN_HSCROLL  );
DA_NUM_TO_STR(EN_VSCROLL  );

#if(_WIN32_WINNT >= 0x0500)
DA_NUM_TO_STR(EN_ALIGN_LTR_EC);
DA_NUM_TO_STR(EN_ALIGN_RTL_EC);
#endif /* _WIN32_WINNT >= 0x0500 */
DA_END_WT_GROUP()

DA_BEG_WT_GROUP(WT_Button)
/*
 * User Button Notification Codes
 */
DA_NUM_TO_STR(BN_CLICKED      );
DA_NUM_TO_STR(BN_PAINT        );
DA_NUM_TO_STR(BN_HILITE       );
DA_NUM_TO_STR(BN_UNHILITE     );
DA_NUM_TO_STR(BN_DISABLE      );
DA_NUM_TO_STR(BN_DOUBLECLICKED);
#if (WINVER >= 0x0400)
DA_NUM_TO_STR(BN_SETFOCUS     );
DA_NUM_TO_STR(BN_KILLFOCUS    );
#endif /* WINVER >= 0x0400 */
DA_END_WT_GROUP()

DA_BEG_WT_GROUP(WT_ListBox)
/*
 * Listbox Notification Codes
 */
DA_NUM_TO_STR(LBN_ERRSPACE );
DA_NUM_TO_STR(LBN_SELCHANGE);
DA_NUM_TO_STR(LBN_DBLCLK   );
DA_NUM_TO_STR(LBN_SELCANCEL);
DA_NUM_TO_STR(LBN_SETFOCUS );
DA_NUM_TO_STR(LBN_KILLFOCUS);
DA_END_WT_GROUP()

DA_BEG_WT_GROUP(WT_ComboBox)
/*
 * Combo Box Notification Codes
 */
DA_NUM_TO_STR(CBN_ERRSPACE    );
DA_NUM_TO_STR(CBN_SELCHANGE   );
DA_NUM_TO_STR(CBN_DBLCLK      );
DA_NUM_TO_STR(CBN_SETFOCUS    );
DA_NUM_TO_STR(CBN_KILLFOCUS   );
DA_NUM_TO_STR(CBN_EDITCHANGE  );
DA_NUM_TO_STR(CBN_EDITUPDATE  );
DA_NUM_TO_STR(CBN_DROPDOWN    );
DA_NUM_TO_STR(CBN_CLOSEUP     );
DA_NUM_TO_STR(CBN_SELENDOK    );
DA_NUM_TO_STR(CBN_SELENDCANCEL);
DA_END_WT_GROUP()

DA_BEG_WT_GROUP_OTHERS()
/* ====== Generic WM_NOTIFY notification codes ================================= */

DA_NUM_TO_STR(NM_OUTOFMEMORY);
DA_NUM_TO_STR(NM_CLICK      );
DA_NUM_TO_STR(NM_DBLCLK     );
DA_NUM_TO_STR(NM_RETURN     );
DA_NUM_TO_STR(NM_RCLICK     );
DA_NUM_TO_STR(NM_RDBLCLK    );
DA_NUM_TO_STR(NM_SETFOCUS   );
DA_NUM_TO_STR(NM_KILLFOCUS  );
#if (_WIN32_IE >= 0x0300)
DA_NUM_TO_STR(NM_CUSTOMDRAW);
DA_NUM_TO_STR(NM_HOVER     );
#endif
#if (_WIN32_IE >= 0x0400)
DA_NUM_TO_STR(NM_NCHITTEST      );
DA_NUM_TO_STR(NM_KEYDOWN        );
DA_NUM_TO_STR(NM_RELEASEDCAPTURE);
DA_NUM_TO_STR(NM_SETCURSOR      );
DA_NUM_TO_STR(NM_CHAR           );
#endif
#if (_WIN32_IE >= 0x0401)
DA_NUM_TO_STR(NM_TOOLTIPSCREATED);
#endif
#if (_WIN32_IE >= 0x0500)
DA_NUM_TO_STR(NM_LDOWN       );
DA_NUM_TO_STR(NM_RDOWN       );
DA_NUM_TO_STR(NM_THEMECHANGED);
#endif
#if _WIN32_WINNT >= 0x0600
DA_NUM_TO_STR(NM_FONTCHANGED         );
DA_NUM_TO_STR(NM_CUSTOMTEXT          );
//DA_NUM_TO_STR(NM_TVSTATEIMAGECHANGING);
#endif
DA_NUM_TO_STR(TBN_GETBUTTONINFOA);
DA_NUM_TO_STR(TBN_BEGINDRAG     );
DA_NUM_TO_STR(TBN_ENDDRAG       );
DA_NUM_TO_STR(TBN_BEGINADJUST   );
DA_NUM_TO_STR(TBN_ENDADJUST     );
DA_NUM_TO_STR(TBN_RESET         );
DA_NUM_TO_STR(TBN_QUERYINSERT   );
DA_NUM_TO_STR(TBN_QUERYDELETE   );
DA_NUM_TO_STR(TBN_TOOLBARCHANGE );
DA_NUM_TO_STR(TBN_CUSTHELP      );
#if (_WIN32_IE >= 0x0300)
DA_NUM_TO_STR(TBN_DROPDOWN);
#endif
#if (_WIN32_IE >= 0x0400)
DA_NUM_TO_STR(TBN_GETOBJECT);

DA_NUM_TO_STR(TBN_HOTITEMCHANGE );
DA_NUM_TO_STR(TBN_DRAGOUT       );
DA_NUM_TO_STR(TBN_DELETINGBUTTON);
DA_NUM_TO_STR(TBN_GETDISPINFOA  );
DA_NUM_TO_STR(TBN_GETDISPINFOW  );
DA_NUM_TO_STR(TBN_GETINFOTIPA   );
DA_NUM_TO_STR(TBN_GETINFOTIPW   );
DA_NUM_TO_STR(TBN_GETBUTTONINFOW);
#if (_WIN32_IE >= 0x0500)
DA_NUM_TO_STR(TBN_RESTORE          );
DA_NUM_TO_STR(TBN_SAVE             );
DA_NUM_TO_STR(TBN_INITCUSTOMIZE    );
DA_NUM_TO_STR(TBNRF_HIDEHELP       );
DA_NUM_TO_STR(TBNRF_ENDCUSTOMIZE   );
#endif /* (_WIN32_IE >= 0x0500) */
#endif

/* status bar notifications */
#if (_WIN32_IE >= 0x0400)
DA_NUM_TO_STR(SBN_SIMPLEMODECHANGE);
#endif

/* PGN_SCROLL Notification Message */
DA_NUM_TO_STR(PGN_SCROLL       );
DA_NUM_TO_STR(PGN_CALCSIZE     );
DA_NUM_TO_STR(PGN_HOTITEMCHANGE);

DA_END_WT_GROUP_OTHERS()