DA_BITMASK_TO_STR(SWP_NOSIZE          ); // 0x0001
DA_BITMASK_TO_STR(SWP_NOMOVE          ); // 0x0002
DA_BITMASK_TO_STR(SWP_NOZORDER        ); // 0x0004
DA_BITMASK_TO_STR(SWP_NOREDRAW        ); // 0x0008
DA_BITMASK_TO_STR(SWP_NOACTIVATE      ); // 0x0010
DA_BITMASK_TO_STR(SWP_FRAMECHANGED    ); // 0x0020  /* The frame changed: send WM_NCCALCSIZE */
DA_BITMASK_TO_STR(SWP_SHOWWINDOW      ); // 0x0040
DA_BITMASK_TO_STR(SWP_HIDEWINDOW      ); // 0x0080
DA_BITMASK_TO_STR(SWP_NOCOPYBITS      ); // 0x0100
DA_BITMASK_TO_STR(SWP_NOOWNERZORDER   ); // 0x0200  /* Don't do owner Z ordering */
DA_BITMASK_TO_STR(SWP_NOSENDCHANGING  ); // 0x0400  /* Don't send WM_WINDOWPOSCHANGING */
